# JSON examples and exercise
****
+ get familiar with packages for dealing with JSON
+ study examples with JSON strings and files 
+ work on exercise to be completed and submitted 
****
+ reference: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
+ data source: http://jsonstudio.com/resources/
****

In [1]:
import pandas as pd

## imports for Python, Pandas

In [2]:
import json
from pandas.io.json import json_normalize

## JSON example, with string

+ demonstrates creation of normalized dataframes (tables) from nested json string
+ source: http://pandas.pydata.org/pandas-docs/stable/io.html#normalization

In [3]:
# define json string
data = [{'state': 'Florida', 
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [4]:
# use normalization to create tables from nested element
json_normalize(data, 'counties')

         name  population
0        Dade       12345
1     Broward       40000
2  Palm Beach       60000
3      Summit        1234
4    Cuyahoga        1337

In [5]:
# further populate tables created from nested element
json_normalize(data, 'counties', ['state', 'shortname', ['info', 'governor']])

         name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich

****
## JSON example, with file

+ demonstrates reading in a json file as a string and as a table
+ uses small sample file containing data about projects funded by the World Bank 
+ data source: http://jsonstudio.com/resources/

In [6]:
# load json as string
json.load((open('data/world_bank_projects_less.json')))

[{'_id': {'$oid': '52b213b38594d8a2be17c780'},
  'approvalfy': 1999,
  'board_approval_month': 'November',
  'boardapprovaldate': '2013-11-12T00:00:00Z',
  'borrower': 'FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA',
  'closingdate': '2018-07-07T00:00:00Z',
  'country_namecode': 'Federal Democratic Republic of Ethiopia!$!ET',
  'countrycode': 'ET',
  'countryname': 'Federal Democratic Republic of Ethiopia',
  'countryshortname': 'Ethiopia',
  'docty': 'Project Information Document,Indigenous Peoples Plan,Project Information Document',
  'envassesmentcategorycode': 'C',
  'grantamt': 0,
  'ibrdcommamt': 0,
  'id': 'P129828',
  'idacommamt': 130000000,
  'impagency': 'MINISTRY OF EDUCATION',
  'lendinginstr': 'Investment Project Financing',
  'lendinginstrtype': 'IN',
  'lendprojectcost': 550000000,
  'majorsector_percent': [{'Name': 'Education', 'Percent': 46},
   {'Name': 'Education', 'Percent': 26},
   {'Name': 'Public Administration, Law, and Justice', 'Percent': 16},
   {'Name': 'Education', 'Percent': 12}],
  'mjsector_namecode': [{'name': 'Education', 'code': 'EX'},
   {'name': 'Education', 'code': 'EX'},
   {'name': 'Public Administration, Law, and Justice', 'code': 'BX'},
   {'name': 'Education', 'code': 'EX'}],
  'mjtheme': ['Human development'],
  'mjtheme_namecode': [{'name': 'Human development', 'code': '8'},
   {'name': '', 'code': '11'}],
  'mjthemecode': '8,11',
  'prodline': 'PE',
  'prodlinetext': 'IBRD/IDA',
  'productlinetype': 'L',
  'project_abstract': {'cdata': 'The development objective of the Second Phase of General Education Quality Improvement Project for Ethiopia is to improve learning conditions in primary and secondary schools and strengthen institutions at different levels of educational administration. The project has six components. The first component is curriculum, textbooks, assessment, examinations, and inspection. This component will support improvement of learning conditions in grades KG-12 by providing increased access to teaching and learning materials and through improvements to the curriculum by assessing the strengths and weaknesses of the current curriculum. This component has following four sub-components: (i) curriculum reform and implementation; (ii) teaching and learning materials; (iii) assessment and examinations; and (iv) inspection. The second component is teacher development program (TDP). This component will support improvements in learning conditions in both primary and secondary schools by advancing the quality of teaching in general education through: (a) enhancing the training of pre-service teachers in teacher education institutions; and (b) improving the quality of in-service teacher training. This component has following three sub-components: (i) pre-service teacher training; (ii) in-service teacher training; and (iii) licensing and relicensing of teachers and school leaders. The third component is school improvement plan. This component will support the strengthening of school planning in order to improve learning outcomes, and to partly fund the school improvement plans through school grants. It has following two sub-components: (i) school improvement plan; and (ii) school grants. The fourth component is management and capacity building, including education management information systems (EMIS). This component will support management and capacity building aspect of the project. This component has following three sub-components: (i) capacity building for education planning and management; (ii) capacity building for school planning and management; and (iii) EMIS. The fifth component is improving the quality of learning and teaching in secondary schools and universities through the use of information and communications technology (ICT). It has following five sub-components: (i) national policy and institution for ICT in general education; (ii) national ICT infrastructure improvement plan for general education; (iii) develop an integrated monitoring, evaluation, and learning system specifically for the ICT component; (iv) teacher professional development in the use of ICT; and (v) provision of limited number of e-Braille display readers with the possibility to scale up to all secondary education schools based on the successful implementation and usage of the readers. The sixth component is program coordination, monitoring and evaluation, and communication. It will support institutional strengthening by developing capacities in all aspects of program coordination, monitoring and evaluation; a new sub-component on communications will support information sharing for better management and accountability. It has following three sub-components: (i) program coordination; (ii) monitoring and evaluation (M and E); and (iii) communication.'},
  'project_name': 'Ethiopia General Education Quality Improvement Project II',
  'projectdocs': [{'DocTypeDesc': 'Project Information Document (PID),  Vol.',
    'DocType': 'PID',
    'EntityID': '090224b081e545fb_1_0',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b081e545fb_1_0',
    'DocDate': '28-AUG-2013'},
   {'DocTypeDesc': 'Indigenous Peoples Plan (IP),  Vol.1 of 1',
    'DocType': 'IP',
    'EntityID': '000442464_20130920111729',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20130920111729',
    'DocDate': '01-JUL-2013'},
   {'DocTypeDesc': 'Project Information Document (PID),  Vol.',
    'DocType': 'PID',
    'EntityID': '090224b0817b19e2_1_0',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b0817b19e2_1_0',
    'DocDate': '22-NOV-2012'}],
  'projectfinancialtype': 'IDA',
  'projectstatusdisplay': 'Active',
  'regionname': 'Africa',
  'sector': [{'Name': 'Primary education'},
   {'Name': 'Secondary education'},
   {'Name': 'Public administration- Other social services'},
   {'Name': 'Tertiary education'}],
  'sector1': {'Name': 'Primary education', 'Percent': 46},
  'sector2': {'Name': 'Secondary education', 'Percent': 26},
  'sector3': {'Name': 'Public administration- Other social services',
   'Percent': 16},
  'sector4': {'Name': 'Tertiary education', 'Percent': 12},
  'sector_namecode': [{'name': 'Primary education', 'code': 'EP'},
   {'name': 'Secondary education', 'code': 'ES'},
   {'name': 'Public administration- Other social services', 'code': 'BS'},
   {'name': 'Tertiary education', 'code': 'ET'}],
  'sectorcode': 'ET,BS,ES,EP',
  'source': 'IBRD',
  'status': 'Active',
  'supplementprojectflg': 'N',
  'theme1': {'Name': 'Education for all', 'Percent': 100},
  'theme_namecode': [{'name': 'Education for all', 'code': '65'}],
  'themecode': '65',
  'totalamt': 130000000,
  'totalcommamt': 130000000,
  'url': 'http://www.worldbank.org/projects/P129828/ethiopia-general-education-quality-improvement-project-ii?lang=en'},
 {'_id': {'$oid': '52b213b38594d8a2be17c781'},
  'approvalfy': 2015,
  'board_approval_month': 'November',
  'boardapprovaldate': '2013-11-04T00:00:00Z',
  'borrower': 'GOVERNMENT OF TUNISIA',
  'country_namecode': 'Republic of Tunisia!$!TN',
  'countrycode': 'TN',
  'countryname': 'Republic of Tunisia',
  'countryshortname': 'Tunisia',
  'docty': 'Project Information Document,Integrated Safeguards Data Sheet,Integrated Safeguards Data Sheet,Project Information Document,Integrated Safeguards Data Sheet,Project Information Document',
  'envassesmentcategorycode': 'C',
  'grantamt': 4700000,
  'ibrdcommamt': 0,
  'id': 'P144674',
  'idacommamt': 0,
  'impagency': 'MINISTRY OF FINANCE',
  'lendinginstr': 'Specific Investment Loan',
  'lendinginstrtype': 'IN',
  'lendprojectcost': 5700000,
  'majorsector_percent': [{'Name': 'Public Administration, Law, and Justice',
    'Percent': 70},
   {'Name': 'Public Administration, Law, and Justice', 'Percent': 30}],
  'mjsector_namecode': [{'name': 'Public Administration, Law, and Justice',
    'code': 'BX'},
   {'name': 'Public Administration, Law, and Justice', 'code': 'BX'}],
  'mjtheme': ['Economic management', 'Social protection and risk management'],
  'mjtheme_namecode': [{'name': 'Economic management', 'code': '1'},
   {'name': 'Social protection and risk management', 'code': '6'}],
  'mjthemecode': '1,6',
  'prodline': 'RE',
  'prodlinetext': 'Recipient Executed Activities',
  'productlinetype': 'L',
  'project_name': 'TN: DTF Social Protection Reforms Support',
  'projectdocs': [{'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocType': 'PID',
    'EntityID': '000333037_20131024115616',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131024115616',
    'DocDate': '29-MAR-2013'},
   {'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocType': 'ISDS',
    'EntityID': '000356161_20131024151611',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20131024151611',
    'DocDate': '29-MAR-2013'},
   {'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocType': 'ISDS',
    'EntityID': '000442464_20131031112136',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20131031112136',
    'DocDate': '29-MAR-2013'},
   {'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocType': 'PID',
    'EntityID': '000333037_20131031105716',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131031105716',
    'DocDate': '29-MAR-2013'},
   {'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocType': 'ISDS',
    'EntityID': '000356161_20130305113209',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113209',
    'DocDate': '16-JAN-2013'},
   {'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocType': 'PID',
    'EntityID': '000356161_20130305113716',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113716',
    'DocDate': '16-JAN-2013'}],
  'projectfinancialtype': 'OTHER',
  'projectstatusdisplay': 'Active',
  'regionname': 'Middle East and North Africa',
  'sector': [{'Name': 'Public administration- Other social services'},
   {'Name': 'General public administration sector'}],
  'sector1': {'Name': 'Public administration- Other social services',
   'Percent': 70},
  'sector2': {'Name': 'General public administration sector', 'Percent': 30},
  'sector_namecode': [{'name': 'Public administration- Other social services',
    'code': 'BS'},
   {'name': 'General public administration sector', 'code': 'BZ'}],
  'sectorcode': 'BZ,BS',
  'source': 'IBRD',
  'status': 'Active',
  'supplementprojectflg': 'N',
  'theme1': {'Name': 'Other economic management', 'Percent': 30},
  'theme_namecode': [{'name': 'Other economic management', 'code': '24'},
   {'name': 'Social safety nets', 'code': '54'}],
  'themecode': '54,24',
  'totalamt': 0,
  'totalcommamt': 4700000,
  'url': 'http://www.worldbank.org/projects/P144674?lang=en'}]

In [7]:
# load as Pandas dataframe
sample_json_df = pd.read_json('data/world_bank_projects_less.json')
sample_json_df

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Name': 'Education for all', 'Percent': 100}","[{'name': 'Education for all', 'code': '65'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Name': 'Other economic management', 'Percent...","[{'name': 'Other economic management', 'code':...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en

****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [ ]:
### ADRIAN's WORK STARTS HERE ###

In [8]:
import pandas as pd
import numpy as np
import json
from pandas.io.json import json_normalize

In [10]:
# specify file path to world bank data
filepath = 'data/world_bank_projects.json'

In [11]:
# create DataFrame from json file
# Each row of the DataFrame corresponds to a Country's project
# inspect accessible data
json_df = pd.read_json(filepath)
print(json_df.shape)
print(json_df.columns)

(500, 50)
Index(['sector', 'supplementprojectflg', 'projectfinancialtype', 'prodline',
       'mjtheme', 'idacommamt', 'impagency', 'project_name', 'mjthemecode',
       'closingdate', 'totalcommamt', 'id', 'mjsector_namecode', 'docty',
       'sector1', 'lendinginstr', 'countrycode', 'sector2', 'totalamt',
       'mjtheme_namecode', 'boardapprovaldate', 'countryshortname', 'sector4',
       'prodlinetext', 'productlinetype', 'regionname', 'status',
       'country_namecode', 'envassesmentcategorycode', 'project_abstract',
       'approvalfy', 'projectdocs', 'lendprojectcost', 'lendinginstrtype',
       'theme1', 'grantamt', 'themecode', 'borrower', 'sectorcode', 'sector3',
       'majorsector_percent', 'board_approval_month', 'theme_namecode',
       'countryname', 'url', 'source', 'projectstatusdisplay', 'ibrdcommamt',
       'sector_namecode', '_id'],
      dtype='object')

In [12]:
# load json world bank data
wb_data = json.load(open(filepath))

In [32]:
#create DataFrame from nested elements with desired columns
t = json_normalize(wb_data, 'mjtheme_namecode',['project_name','countryname' ])
t.columns = ['code', 'theme', 'project_name', 'countryname']
t = t.sort_values(by=['countryname'])
type(t)
t

,code,theme,project_name,countryname
480,5,Trade and integration,West Africa Regional Communications Infrastruc...,Africa
534,5,Trade and integration,Southern Africa Trade and Transport Facilitati...,Africa
533,5,Trade and integration,Southern Africa Trade and Transport Facilitati...,Africa
483,5,Trade and integration,West Africa Regional Communications Infrastruc...,Africa
482,4,Financial and private sector development,West Africa Regional Communications Infrastruc...,Africa
...,...,...,...,...
149,11,Environment and natural resources management,Red Sea and Gulf of Aden Strategic Ecosystem M...,World
153,11,Environment and natural resources management,Red Sea and Gulf of Aden Strategic Ecosystem M...,World
692,10,Rural development,National Human and Animal Health Systems Asses...,World
152,11,Environment and natural resources management,Red Sea and Gulf of Aden Strategic Ecosystem M...,World
151,11,Environment and natural resources management,Red Sea and Gulf of Aden Strategic Ecosystem M...,World

In [14]:
### PROBLEM 1. Find the 10 countries with most projects

In [33]:
# return top 10 value_counts on t.countryname
df1 = t.countryname.value_counts()
print('Number of countries with projects: ', df1.shape)
df1.head(10)

Number of countries with projects:  (118,)

Republic of Indonesia              56
Republic of India                  51
Socialist Republic of Vietnam      43
Federative Republic of Brazil      41
People's Republic of Bangladesh    41
People's Republic of China         40
Africa                             39
Republic of Yemen                  34
Kingdom of Morocco                 32
Republic of Mozambique             31
Name: countryname, dtype: int64

In [16]:
### PROBLEM 2. Find the top 10 major project themes (using column 'mjtheme_namecode')

In [17]:
# print top 10 project themes
# head arg=11 because empty project themes were grouped and counted together
df2 = t.theme.value_counts()
df2.head(11)

Environment and natural resources management    223
Rural development                               202
Human development                               197
Public sector governance                        184
Social protection and risk management           158
Financial and private sector development        130
                                                122
Social dev/gender/inclusion                     119
Trade and integration                            72
Urban development                                47
Economic management                              33
Name: theme, dtype: int64

In [18]:
### PROBLEM 3. In 2. above you will notice that some entries have only the code and the name is missing. 
#Create a dataframe with the missing names filled in.

In [19]:
df3 = t.sort_values(by=['code'])
df3

,code,theme,project_name,countryname
1024,1,,TANZANIA SECOND CENTRAL TRANSP CORRIDOR PROJEC...,United Republic of Tanzania
453,1,Economic management,LS- First Growth and Competitiveness DPG,Kingdom of Lesotho
647,1,Economic management,LAOSTAT-STRENGTHENING THE NATIONAL STATISTICAL...,Lao People's Democratic Republic
1235,1,Economic management,Public Sector Management and Social Inclusion ...,Oriental Republic of Uruguay
220,1,Economic management,Tunisia - Communications for policy reforms,Republic of Tunisia
...,...,...,...,...
194,9,Urban development,Burkina Faso Electricity Sector Support Project,Burkina Faso
1102,9,Urban development,Productive and Sustainable Cities Development ...,Republic of Colombia
739,9,Urban development,Local Governance and Service Delivery Project,Republic of South Sudan
333,9,,China: Nanchang Urban Rail Project,People's Republic of China
1303,9,Urban development,BO Urban Infrastructure Project (II) Additiona...,Plurinational State of Bolivia

In [20]:
# DataFrame of all rows with missing themes
empties = df3[df3.theme=='']
empties

,code,theme,project_name,countryname
1024,1,,TANZANIA SECOND CENTRAL TRANSP CORRIDOR PROJEC...,United Republic of Tanzania
1437,1,,Strengthening the resilience capacity of Maya ...,Republic of Guatemala
1114,1,,Disaster Risk Management Project,Republic of Honduras
212,1,,Liberia EITI - Post Compliance I,Republic of Liberia
363,1,,CI - 27 Gas Field Expansion,Republic of Cote d'Ivoire
...,...,...,...,...
1483,8,,Nepal: Pilot Project for Seismic School Safety...,Nepal
976,8,,Sierra Leone Energy Access Project - Sierra Le...,Republic of Sierra Leone
471,9,,Guangxi Laibin Water Environment Project,People's Republic of China
460,9,,"Fostering Innovation through Research, Science...",Socialist Republic of Vietnam
333,9,,China: Nanchang Urban Rail Project,People's Republic of China

In [21]:
#Themes correspond to the code columns
#identify code: theme pairs
pairs = set(zip(df3.code, df3.theme))
pairs = [pair for pair in pairs if pair[1]!='']
pairs = dict(pairs)
pairs

{'9': 'Urban development',
 '7': 'Social dev/gender/inclusion',
 '4': 'Financial and private sector development',
 '3': 'Rule of law',
 '8': 'Human development',
 '2': 'Public sector governance',
 '5': 'Trade and integration',
 '6': 'Social protection and risk management',
 '11': 'Environment and natural resources management',
 '10': 'Rural development',
 '1': 'Economic management'}

In [22]:
# map pairs to theme column ot fill missing values
df3.theme = df3.code.map(pairs)

In [29]:
# An empty dataframe if all empty theme rows have been filled accordingly
empties2 = df3[df3.theme == '']
print(empties2.shape)
empties2

(0, 4)

Empty DataFrame
Columns: [code, theme, project_name, countryname]
Index: []

In [35]:
# recaluculate solution to problem 2 with mapped themes
df3.theme.value_counts().head(10)

Environment and natural resources management    250
Rural development                               216
Human development                               210
Public sector governance                        199
Social protection and risk management           168
Financial and private sector development        146
Social dev/gender/inclusion                     130
Trade and integration                            77
Urban development                                50
Economic management                              38
Name: theme, dtype: int64